name: CI/CD

on:
    pull_request:
        branches: [ master ]

jobs:
    examples-builds:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/brushfam/typechain-polkadot-ci
            options: --user root
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Yarn Install dependencies
              run: |
                  yarn install
            - name: Run example builds
              run: |
                  chown -R root .
                  chmod -R a+rwx .
                  bash ./examples.sh
    eslint:
        needs: examples-builds
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/brushfam/typechain-polkadot-ci
            options: --user root
        steps:
            - uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - name: Yarn Install dependencies
              run: |
                  yarn install
            - name: Run ESLint
              run: |
                  chown -R root .
                  chmod -R a+rwx .
                  yarn lint
    integration-tests:
        needs: eslint
        concurrency:
            group: integration-tests-${{ github.ref }}
            cancel-in-progress: true
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/brushfam/typechain-polkadot-ci
            options: --user root
        steps:
            - uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - name: Yarn install dependencies
              run: |
                  yarn install
            - name: Run Test Jest
              run: |
                  chown -R root .
                  chmod -R a+rwx .
                  set +e
                  substrate-contracts-node --tmp --dev & P1=$!;
                  set -e
                  yarn test
                  kill $P1
              timeout-minutes: 3
